name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  tests:
    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }} (${{ matrix.dependencies }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
        symfony: [ '6.4.*', '7.4.*', '8.0.*', '8.1.*' ]
        dependencies: [ 'highest' ]
        include:
          - php: '8.2'
            symfony: '6.4.*'
            dependencies: 'lowest'
          - php: '8.2'
            symfony: '7.4.*'
            dependencies: 'lowest'
          - php: '8.2'
            symfony: '8.0.*'
            dependencies: 'lowest'
          - php: '8.2'
            symfony: '8.1.*'
            dependencies: 'lowest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Symfony
        run: |
          composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run checks
        run: composer check
